/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.parland.damas;

import java.util.ArrayList;

import org.w3c.dom.events.MouseEvent;

/**
 *
 * @author Usuario
 */
public class DamasGUID extends javax.swing.JFrame {

    /**
     * Creates new form DamasGUID
     */
    ArrayList[][] tablero;

    public DamasGUID() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadControls() {
        tablero = new ArrayList[8][8];

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        APeon1 = new javax.swing.JButton();
        APeon2 = new javax.swing.JButton();
        APeon3 = new javax.swing.JButton();
        APeon4 = new javax.swing.JButton();
        APeon5 = new javax.swing.JButton();
        APeon6 = new javax.swing.JButton();
        APeon7 = new javax.swing.JButton();
        APeon8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        APeon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon1.setBorder(null);
        APeon1.setBorderPainted(false);
        APeon1.setContentAreaFilled(false);
        APeon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APeon1MouseClicked(evt);
            }
        });
        APeon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APeon1ActionPerformed(evt);
            }
        });
        jPanel1.add(APeon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 686, 90, 90));

        APeon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon2.setBorder(null);
        APeon2.setBorderPainted(false);
        APeon2.setContentAreaFilled(false);
        APeon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APeon2MouseClicked(evt);
            }
        });
        APeon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APeon2ActionPerformed(evt);
            }
        });
        jPanel1.add(APeon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 90, 90));

        APeon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon3.setBorder(null);
        APeon3.setBorderPainted(false);
        APeon3.setContentAreaFilled(false);
        APeon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APeon3MouseClicked(evt);
            }
        });
        APeon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APeon3ActionPerformed(evt);
            }
        });
        jPanel1.add(APeon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 686, 90, 90));

        APeon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon4.setBorder(null);
        APeon4.setBorderPainted(false);
        APeon4.setContentAreaFilled(false);
        APeon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APeon4MouseClicked(evt);
            }
        });
        APeon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APeon4ActionPerformed(evt);
            }
        });
        jPanel1.add(APeon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 590, 90, 90));

        APeon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon5.setBorder(null);
        APeon5.setBorderPainted(false);
        APeon5.setContentAreaFilled(false);
        APeon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APeon5MouseClicked(evt);
            }
        });
        jPanel1.add(APeon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 686, 90, 90));

        APeon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon6.setBorder(null);
        APeon6.setBorderPainted(false);
        APeon6.setContentAreaFilled(false);
        APeon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APeon6MouseClicked(evt);
            }
        });
        jPanel1.add(APeon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 590, 90, 90));

        APeon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon7.setBorder(null);
        APeon7.setBorderPainted(false);
        APeon7.setContentAreaFilled(false);
        APeon7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APeon7ActionPerformed(evt);
            }
        });
        jPanel1.add(APeon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 686, 90, 90));

        APeon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaJugador.png"))); // NOI18N
        APeon8.setBorder(null);
        APeon8.setBorderPainted(false);
        APeon8.setContentAreaFilled(false);
        jPanel1.add(APeon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 590, 90, 90));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 14, 90, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 14, 90, 90));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 14, 90, 90));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 14, 90, 90));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 110, 90, 90));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 110, 90, 90));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 110, 90, 90));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 110, 90, 90));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 206, 90, 90));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton10.setContentAreaFilled(false);
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 206, 90, 90));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 206, 90, 90));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PiezaRival.png"))); // NOI18N
        jButton12.setContentAreaFilled(false);
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 206, 90, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tablero.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 770, 770));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void APeon7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_APeon7ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_APeon7ActionPerformed

    private void APeon4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_APeon4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_APeon4ActionPerformed

    private void APeon4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_APeon4MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            this.APeon4.setLocation(this.APeon4.getX() + 96, this.APeon4.getY() - 96);
        } else if (evt.getButton() == 1) {
            this.APeon4.setLocation(this.APeon4.getX() - 96, this.APeon4.getY() - 96);
        }
    }// GEN-LAST:event_APeon4MouseClicked

    private void APeon5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_APeon5MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            this.APeon5.setLocation(this.APeon5.getX() + 96, this.APeon5.getY() - 96);
        } else if (evt.getButton() == 1) {
            this.APeon5.setLocation(this.APeon5.getX() - 96, this.APeon5.getY() - 96);
        }
    }// GEN-LAST:event_APeon5MouseClicked

    private void APeon6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_APeon6MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            this.APeon6.setLocation(this.APeon6.getX() + 96, this.APeon6.getY() - 96);
        } else if (evt.getButton() == 1) {
            this.APeon6.setLocation(this.APeon6.getX() - 96, this.APeon6.getY() - 96);
        }
    }// GEN-LAST:event_APeon6MouseClicked

    private void APeon1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Peon2MouseClicked
        // TODO add your handling code here:
        Ficha peon1 = new Ficha(this.APeon1.getX(), this.APeon1.getY(), false);
        Ficha peon2 = new Ficha(this.APeon2.getX(), this.APeon2.getY(), false);

        if (evt.getButton() == 3) {
            if ((peon1.getX() + 96 & peon1.getY() - 96) == (peon2.getX() & peon2.getY())) {
                System.out.println("Hay una pieza aqui");
            } else {
                this.APeon1.setLocation(this.APeon1.getX() + 96, this.APeon1.getY() - 96);
            }

        } else if (evt.getButton() == 1) {
            this.APeon1.setLocation(this.APeon1.getX() - 96, this.APeon1.getY() - 96);
        }
    }// GEN-LAST:event_Peon2MouseClicked

    private void APeon1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Peon2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Peon2ActionPerformed

    private void APeon2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Peon2MouseClicked
        // TODO add your handling code here:

        if (evt.getButton() == 3) {
            System.out.println(this.getComponentAt(this.APeon2.getX() + 96, this.APeon2.getY() - 96));
            this.APeon2.setLocation(this.APeon2.getX() + 96, this.APeon2.getY() - 96);
        } else if (evt.getButton() == 1) {
            this.APeon2.setLocation(this.APeon2.getX() - 96, this.APeon2.getY() - 96);
        }
    }// GEN-LAST:event_Peon2MouseClicked

    private void APeon2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Peon2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Peon2ActionPerformed

    private void APeon3MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Peon3MouseClicked
        // TODO add your handling code here:
        movimientoAzul(this.APeon3, evt);
    }// GEN-LAST:event_Peon3MouseClicked

    private void APeon3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Peon3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Peon3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void nuevasFichas(){
        Ficha peon1 = new Ficha(this.APeon1.getX(), this.APeon1.getY(), false);
        Ficha peon2 = new Ficha(this.APeon2.getX(), this.APeon2.getY(), false);
    }
    public void movimientoAzul(javax.swing.JButton pieza, java.awt.event.MouseEvent evt){
        if (evt.getButton() == 3) {
            pieza.setLocation(pieza.getX() + 96, pieza.getY() - 96);
        } else if (evt.getButton() == 1) {
            pieza.setLocation(pieza.getX() - 96, pieza.getY() - 96);
        }
    }
    public boolean espacioVacio(Ficha peon, int posicionXIzq, int posicionYIzq, int posicionXDer, int posicionYDer){
        boolean vacio;
        if (true) {
            System.out.println("Hay una pieza aqui");
            vacio = false;
        }
        return vacio;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DamasGUID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DamasGUID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DamasGUID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DamasGUID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DamasGUID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APeon1;
    private javax.swing.JButton APeon2;
    private javax.swing.JButton APeon3;
    private javax.swing.JButton APeon4;
    private javax.swing.JButton APeon5;
    private javax.swing.JButton APeon6;
    private javax.swing.JButton APeon7;
    private javax.swing.JButton APeon8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
